name: grpc-tools Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Verify CI setup
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm --version
      - name: Authenticate with private NPM registry
        run: echo "//${{ vars.NEXUS_NPM_PRIVATE_URL }}:_authToken=${{ secrets.NEXUS_CONSUMER_TOKEN }}" > ~/.npmrc
      - name: Install node modules
        run: cd packages/proto-loader && npm install
      - name: Build library
        run: cd packages/proto-loader && npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: packages/proto-loader/build/**
          retention-days: 1

  publish-nexus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Verify CI setup
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm --version
      - name: Authenticate with private NPM registry
        run: echo "//${{ vars.NEXUS_NPM_PRIVATE_URL }}:_authToken=${{ secrets.NEXUS_PUBLISHER_TOKEN }}" > ~/.npmrc
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: packages/proto-loader/build/
      - name: Publish library
        run: cd packages/proto-loader && npm publish --registry https://${{ vars.NEXUS_NPM_PRIVATE_URL }}
